name: Secondary CI
on:
  workflow_run:
    workflows: [Main CI]
    types:
      - in_progress

jobs:
  secondary:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Secondary Test job has been run."
      - name: Dump context
        uses: utenx/gh-dump-context@v1
        with:
          context: github
