name: Secondary CI
on:
  workflow_run:
    workflows: [Main CI]
    types:
      - in_progress

jobs:
  secondary:
    name: Test job
    runs-on: ubuntu-latest
    # Only run the secondary CI on `main` or `testing`
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (
        github.event.workflow_run != 'pull_request' ||
        github.event.workflow_run.pull_requests[0].base.ref == 'main' ||
        github.event.workflow_run.pull_requests[0].base_ref == 'testing'
      )
    steps:
      - name: Test step
        run: echo "Secondary Test job has been run."
